usr/lib/mono/gac/Mono.Addins.Gui/*/*		/usr/lib/cli/Mono.Addins.Gui-0.2/
usr/lib/mono/gac/policy.0.2.Mono.Addins.Gui/*/*	/usr/lib/cli/Mono.Addins.Gui-0.2/
usr/lib/mono/gac/policy.0.3.Mono.Addins.Gui/*/*	/usr/lib/cli/Mono.Addins.Gui-0.2/
usr/lib/mono/gac/policy.0.4.Mono.Addins.Gui/*/*	/usr/lib/cli/Mono.Addins.Gui-0.2/
usr/lib/mono/gac/policy.0.5.Mono.Addins.Gui/*/*	/usr/lib/cli/Mono.Addins.Gui-0.2/
usr/lib/mono/gac/policy.0.6.Mono.Addins.Gui/*/*	/usr/lib/cli/Mono.Addins.Gui-0.2/
