usr/lib/mono/gac/Mono.Addins.MSBuild/*/*			/usr/lib/cli/Mono.Addins.MSBuild-0.2/
usr/lib/mono/gac/policy.0.2.Mono.Addins.MSBuild/*/*		/usr/lib/cli/Mono.Addins.MSBuild-0.2/
usr/lib/mono/gac/policy.0.3.Mono.Addins.MSBuild/*/*		/usr/lib/cli/Mono.Addins.MSBuild-0.2/
usr/lib/mono/gac/policy.0.4.Mono.Addins.MSBuild/*/*		/usr/lib/cli/Mono.Addins.MSBuild-0.2/
usr/lib/mono/gac/policy.0.5.Mono.Addins.MSBuild/*/*		/usr/lib/cli/Mono.Addins.MSBuild-0.2/
usr/lib/mono/gac/policy.0.6.Mono.Addins.MSBuild/*/*		/usr/lib/cli/Mono.Addins.MSBuild-0.2/
